version: "3.3"
services:
  etherwrapper:
    container_name: etherwrapper-solo
    environment:
      - BASE_PATH=
    volumes:
      - ./wrapper:/app
    build:
      context: ./wrapper
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "${WRAPPER_SOLODEVPORT}:${WRAPPER_PORT}"
    networks:
      - default
  etherpad:
    container_name: etherpad-solo
    build:
      context: ./etherpad
      dockerfile: Dockerfile
      args:
        - ETHERPAD_API_KEY=${ETHERPAD_API_KEY}
    ports:
      - "${ETHERPAD_SOLODEVPORT}:${ETHERPAD_PORT}"
    networks:
      - default