version: "3.3"
services:
  etherwrapper:
    container_name: etherwrapper-production
    image: 'etherwrapperprod:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - PORT=${WRAPPER_PORT}
      - BASE_PATH=/etherwrapper
      - MONGODB_URL=mongoprodurl
    build:
      context: ./etherwrapper
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      etherpad:
        condition: service_healthy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not
          set}-etherwrapper-http.rule=PathPrefix(`/etherwrapper`)
        - traefik.http.routers.${STACK_NAME?Variable not
          set}-etherwrapper-http.middlewares=etherwrapper-stripprefix
        - traefik.http.middlewares.etherwrapper-stripprefix.stripprefix.prefixes=/etherwrapper
        - traefik.http.services.${STACK_NAME?Variable not
          set}-etherwrapper.loadbalancer.server.port=${WRAPPER_PORT}
    networks:
      - traefik-public

  etherpad:
    container_name: etherpad-production
    image: 'etherpad:${TAG-latest}'
    build:
      context: ./etherpad
      dockerfile: Dockerfile
      args:
        - ETHERPAD_API_KEY=${ETHERPAD_API_KEY}
    env_file:
      - .env
    environment:
      - TITLE=${ETHERPAD_TITLE}
      - PORT=${ETHERPAD_PORT}
      - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
      - ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD}
      - ADMIN_USER=${ETHERPAD_ADMIN_USER}
      - REQUIRE_SESSION=${ETHERPAD_REQUIRE_SESSION}
      - EDIT_ONLY=${ETHERPAD_EDIT_ONLY}
      - MONGODB_URL=mongoprodurl

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not
          set}-etherpad-http.rule=PathPrefix(`/etherpad`)
        - traefik.http.routers.${STACK_NAME?Variable not
          set}-etherpad-http.middlewares=etherpad-stripprefix
        - traefik.http.middlewares.etherpad-stripprefix.stripprefix.prefixes=/etherpad
        - traefik.http.services.${STACK_NAME?Variable not
          set}-etherpad.loadbalancer.server.port=${ETHERPAD_PORT}

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
