version: "3.3"
services:
  etherwrapper:
    container_name: ${WRAPPER_HOST}-production
    image: '${WRAPPER_HOST}:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - PORT=${WRAPPER_PORT}
      # Allow explicit env var override for tests
    build:
      context: ./${WRAPPER_HOST}
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      - ${ETHERPAD_HOST}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not set}-${WRAPPER_HOST}-http.rule=PathPrefix(`/${WRAPPER_HOST}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-${WRAPPER_HOST}-http.middlewares=${WRAPPER_HOST}-stripprefix
        - traefik.http.middlewares.${WRAPPER_HOST}-stripprefix.stripprefix.prefixes=/${WRAPPER_HOST}
        - traefik.http.services.${STACK_NAME?Variable not set}-${WRAPPER_HOST}.loadbalancer.server.port=${WRAPPER_PORT}
    networks:
      - traefik-public
      - default

  etherpad:
    container_name: ${ETHERPAD_HOST}-production
    image: '${ETHERPAD_HOST}:${TAG-latest}'
    build:
      context: ./${ETHERPAD_HOST}
      dockerfile: Dockerfile
      args:
        - ETHERPAD_API_KEY=${ETHERPAD_API_KEY}
    env_file:
      - .env
    environment:
      - TITLE=${ETHERPAD_TITLE}
      - PORT=${ETHERPAD_PORT}
      - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
      - ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD}
      - ADMIN_USER=${ETHERPAD_ADMIN_USER}
      - REQUIRE_SESSION=${ETHERPAD_REQUIRE_SESSION}
      - EDIT_ONLY=${ETHERPAD_EDIT_ONLY}
    depends_on:
      mongodb:
         condition: service_healthy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not set}-${ETHERPAD_HOST}-http.rule=PathPrefix(`/${ETHERPAD_HOST}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-${ETHERPAD_HOST}-http.middlewares=${ETHERPAD_HOST}-stripprefix
        - traefik.http.middlewares.${ETHERPAD_HOST}-stripprefix.stripprefix.prefixes=/${ETHERPAD_HOST}
        - traefik.http.services.${STACK_NAME?Variable not set}-${ETHERPAD_HOST}.loadbalancer.server.port=${ETHERPAD_PORT}

    networks:
      - traefik-public
      - default
      
  mongodb:
      image: bitnami/mongodb:latest
      container_name: etherpad-mongodb
      environment:
        - MONGODB_USERNAME
        - MONGODB_PASSWORD
        - MONGODB_DATABASE
        - MONGODB_ROOT_PASSWORD
      networks:
        - default
      healthcheck:
        test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p $MONGODB_ROOT_PASSWORD --quiet | grep 1
        interval: 10s
        timeout: 10s
        retries: 3
        start_period: 20s

networks:
  traefik-public:
    external: true