name: build-and-publish-docker

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Image Ceditor
        id: docker_build_ceditor
        uses: docker/build-push-action@v2
        with:
          context: ./ceditor/.
          file: ceditor/Dockerfile
          push: true
          tags: interlinkproject/interlinker-etherpad:ceditor-latest
          cache-from: type=registry,ref=interlinkproject/interlinker-etherpad:ceditor-buildcache
          cache-to: type=registry,ref=interlinkproject/interlinker-etherpad:ceditor-buildcache,mode=max
      - name: Build and push Docker Image Etherpad
        id: docker_build_etherpad
        uses: docker/build-push-action@v2
        with:
          context: ./etherpad/.
          file: etherpad/Dockerfile
          push: true
          tags: interlinkproject/interlinker-etherpad:etherpad-latest
          cache-from: type=registry,ref=interlinkproject/interlinker-etherpad:etherpad-buildcache
          cache-to: type=registry,ref=interlinkproject/interlinker-etherpad:etherpad-buildcache,mode=max
      - name: Trigger Dev Deployment
        uses: octokit/request-action@v2.x
        id: trigger_dev_deployment
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: interlink-project
          repo: interlink-project
          event_type: update-dev-environment
        env:
          GITHUB_TOKEN: ${{ secrets.INTERLINK_PROJECT_GITHUB_TOKEN }}